import json
import logging
from typing import (
    Type,
    Tuple,
)

from langchain_core.callbacks import CallbackManagerForToolRun
from langchain_core.tools import ToolException
from pydantic import BaseModel, Field

from ttyg.utils import timeit
from .base import BaseGraphDBTool
from .sparql_query_artifact import SparqlQueryArtifact


class SparqlQueryTool(BaseGraphDBTool):
    """
    Tool, which executes SPARQL queries generated by the agent.
    """

    class SearchInput(BaseModel):
        query: str = Field(
            description="A valid SPARQL SELECT, CONSTRUCT, DESCRIBE or ASK query without prefixes"
        )

    name: str = "sparql_query"
    description: str = "Query GraphDB by SPARQL SELECT, CONSTRUCT, DESCRIBE or ASK query and return result."
    args_schema: Type[BaseModel] = SearchInput
    response_format: str = "content_and_artifact"

    @timeit
    def _run(
        self,
        query: str,
        validation: bool = True,
        run_manager: CallbackManagerForToolRun | None = None,
    ) -> Tuple[str, SparqlQueryArtifact]:
        try:
            logging.debug(f"Executing SPARQL query {query}")
            query_results, actual_query = self.graph.eval_sparql_query(
                self.graphdb_repository_id, query, validation=validation
            )
            if query_results.type in ("CONSTRUCT", "DESCRIBE"):
                return (query_results.serialize(format="turtle", encoding="utf-8").decode("utf-8"),
                        SparqlQueryArtifact(query=actual_query))
            query_results_as_json = query_results.serialize(format="json", encoding="utf-8").decode("utf-8")
            return json.dumps(json.loads(query_results_as_json), indent=2), SparqlQueryArtifact(query=actual_query)
        except Exception as e:
            raise ToolException(str(e))
