name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ttyg
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install dependencies with Poetry
        shell: bash -l {0}
        run: |
          conda activate ttyg
          poetry install --no-interaction --with test

      - name: Start GraphDB
        run: |
          cd docker
          ./start.sh

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate ttyg
          poetry run pytest --cov=ttyg --cov-report=term-missing tests/unit_tests/

      - name: Clean up Docker Compose
        if: always()
        run: |
          cd docker
          docker compose down -v --remove-orphans
